import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  backgroundDecorations: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
  },
  floatingElement: {
    position: "absolute",
  },
  star1: {
    top: 100,
    left: 50,
  },
  star2: {
    top: 160,
    right: 70,
  },
  star3: {
    top: 220,
    left: 80,
  },
  decorationText: {
    fontSize: 18,
    opacity: 0.3,
  },
  inner: {
    flex: 1,
    paddingHorizontal: 32,
    paddingTop: 80,
    paddingBottom: 40,
    zIndex: 2,
  },
  headerSection: {
    alignItems: "center",
    marginBottom: 80,
  },
  mainTitle: {
    fontSize: 42,
    fontWeight: "900",
    color: "#fff",
    letterSpacing: 3,
    textShadowColor: "rgba(0,0,0,0.3)",
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 6,
    marginBottom: 16,
    fontFamily: Platform.OS === "ios" ? "PingFang SC" : "sans-serif-medium",
  },
  subtitle: {
    fontSize: 16,
    color: "rgba(255,255,255,0.8)",
    fontWeight: "500",
    letterSpacing: 1,
  },
  inputSection: {
    flex: 1,
    justifyContent: "center",
    marginBottom: 40,
  },
  inputGroup: {
    marginBottom: 24,
  },
  inputLabel: {
    fontSize: 16,
    color: "#fff",
    fontWeight: "600",
    marginBottom: 12,
    marginLeft: 4,
  },
  phoneInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.15)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
    paddingHorizontal: 16,
  },
  countryCode: {
    fontSize: 16,
    color: "#fff",
    fontWeight: "600",
    marginRight: 12,
    paddingRight: 12,
    borderRightWidth: 1,
    borderRightColor: "rgba(255,255,255,0.3)",
  },
  phoneInput: {
    flex: 1,
    height: 52,
    fontSize: 16,
    color: "#fff",
    fontWeight: "500",
    // @ts-ignore - Web-only property
    outlineStyle: "none",
  },
  codeInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.15)",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
    paddingLeft: 16,
    paddingRight: 10,
    height: 54,
  },
  codeInput: {
    height: 52,
    fontSize: 16,
    color: "#fff",
    fontWeight: "500",
    outlineStyle: "none",
  },
  captchaButton: {
    marginLeft: 12,
    height: 38,
    width: 100,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    overflow: "hidden",
  },
  sendCodeButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 12,
    marginRight: 8,
  },
  disabledSendButton: {
    opacity: 0.5,
  },
  sendCodeText: {
    fontSize: 14,
    color: "#fff",
    fontWeight: "600",
  },
  bottomSection: {
    alignItems: "center",
  },
  loginButton: {
    width: "100%",
    height: 56,
    borderRadius: 28,
    overflow: "hidden",
    marginBottom: 24,
    shadowColor: "#ff6b6b",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  disabledButton: {
    opacity: 0.5,
    shadowOpacity: 0.1,
  },
  buttonGradient: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  loadingContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  loadingText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  agreementText: {
    fontSize: 12,
    color: "rgba(255,255,255,0.6)",
    textAlign: "center",
    lineHeight: 16,
    paddingHorizontal: 20,
  },
});
