import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#191000",
    overflow: "hidden",
  },
  backgroundImage: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
  },
  backgroundDecorations: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
  },
  inner: {
    flex: 1,
    paddingHorizontal: 32,
    paddingTop: 60,
    paddingBottom: 40,
    zIndex: 2,
    justifyContent: "space-between",
  },

  /* ---- 顶部境界 ---- */
  topSection: {
    alignItems: "center",
    marginBottom: 8,
  },
  levelBadgeWrapper: {
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderRadius: 20,
  },
  levelGlow: {
    position: "absolute",
    width: 180,
    height: 50,
    borderRadius: 25,
    backgroundColor: "rgba(255, 160, 20, 0.5)",
    shadowColor: "#FF8C00",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 20,
    elevation: 12,
  },
  levelBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 28,
    paddingVertical: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 220, 100, 0.6)",
  },
  levelIcon: {
    fontSize: 20,
    marginRight: 8,
  },
  levelText: {
    fontSize: 20,
    fontWeight: "800",
    color: "#fff",
    letterSpacing: 4,
    textShadowColor: "rgba(0,0,0,0.3)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
    fontFamily: Platform.OS === "ios" ? "PingFang SC" : "sans-serif-medium",
  },
  shimmerOverlay: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 40,
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    transform: [{ skewX: "-20deg" }],
  },

  /* ---- 宠物展示区 ---- */
  petSection: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    position: "relative",
  },
  auraRingOuter: {
    position: "absolute",
    width: 320,
    height: 320,
    borderRadius: 160,
    borderWidth: 2,
    borderColor: "rgba(255, 200, 80, 0.4)",
    backgroundColor: "rgba(255, 200, 80, 0.05)",
  },
  auraRingInner: {
    position: "absolute",
    width: 250,
    height: 250,
    borderRadius: 125,
    borderWidth: 1.5,
    borderColor: "rgba(255, 180, 50, 0.5)",
    backgroundColor: "rgba(255, 180, 50, 0.08)",
  },
  bottomGlow: {
    position: "absolute",
    bottom: 40,
    width: 200,
    height: 30,
    borderRadius: 100,
    backgroundColor: "rgba(255, 200, 80, 0.5)",
    shadowColor: "#FFD700",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 25,
    elevation: 15,
  },
  petContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  petImage: {
    width: 200,
    height: 200,
  },
  petEmoji: {
    fontSize: 100,
    textShadowColor: "rgba(0,0,0,0.3)",
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 8,
  },
  petName: {
    fontSize: 28,
    fontWeight: "900",
    color: "#fff",
    letterSpacing: 2,
    textShadowColor: "rgba(0,0,0,0.6)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
    fontFamily: Platform.OS === "ios" ? "PingFang SC" : "sans-serif-medium",
  },

  /* ---- 底部按钮 ---- */
  bottomSection: {
    alignItems: "center",
    paddingTop: 8,
  },
  enterButton: {
    width: "100%",
    height: 56,
    borderRadius: 28,
    overflow: "hidden",
    shadowColor: "#F2994A",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
  },
  buttonGradient: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    letterSpacing: 1,
  },
});
